// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admin-layout/CardsFirst.tsx": () => import("../components/mockups/admin-layout/CardsFirst.tsx"),
  "./components/mockups/admin-layout/CommandCenter.tsx": () => import("../components/mockups/admin-layout/CommandCenter.tsx"),
  "./components/mockups/admin-layout/SplitPane.tsx": () => import("../components/mockups/admin-layout/SplitPane.tsx")
};
