import { pgTable, text, serial, timestamp, integer, numeric, boolean, date, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const runsTable = pgTable("runs", {
  id: serial("id").primaryKey(),
  userId: text("user_id"),
  profileId: integer("profile_id"),
  vehicleId: integer("vehicle_id"),
  venueId: integer("venue_id"),
  showDate: date("show_date"),
  status: text("status").notNull().default("draft"),
  actType: text("act_type"),
  origin: text("origin"),
  originLat: numeric("origin_lat", { precision: 10, scale: 6 }),
  originLng: numeric("origin_lng", { precision: 10, scale: 6 }),
  destination: text("destination"),
  destinationLat: numeric("destination_lat", { precision: 10, scale: 6 }),
  destinationLng: numeric("destination_lng", { precision: 10, scale: 6 }),
  distanceKm: numeric("distance_km", { precision: 10, scale: 2 }).notNull().default("0"),
  returnTrip: boolean("return_trip").notNull().default(false),
  fuelPrice: numeric("fuel_price", { precision: 6, scale: 3 }).notNull().default("0"),
  showType: text("show_type").notNull().default("flat_fee"),
  fee: numeric("fee", { precision: 10, scale: 2 }),
  capacity: integer("capacity"),
  ticketPrice: numeric("ticket_price", { precision: 8, scale: 2 }),
  expectedAttendancePct: numeric("expected_attendance_pct", { precision: 5, scale: 2 }),
  dealType: text("deal_type"),
  splitPct: numeric("split_pct", { precision: 5, scale: 2 }),
  guarantee: numeric("guarantee", { precision: 10, scale: 2 }),
  merchEstimate: numeric("merch_estimate", { precision: 10, scale: 2 }),
  marketingCost: numeric("marketing_cost", { precision: 10, scale: 2 }),
  bookingFeePerTicket: numeric("booking_fee_per_ticket", { precision: 8, scale: 2 }),
  supportActCost: numeric("support_act_cost", { precision: 10, scale: 2 }),
  accommodationRequired: boolean("accommodation_required").notNull().default(false),
  accommodationType: text("accommodation_type"),
  singleRooms: integer("single_rooms"),
  doubleRooms: integer("double_rooms"),
  accommodationNights: numeric("accommodation_nights", { precision: 5, scale: 1 }),
  accommodationCost: numeric("accommodation_cost", { precision: 10, scale: 2 }),
  foodCost: numeric("food_cost", { precision: 10, scale: 2 }),
  extraCosts: numeric("extra_costs", { precision: 10, scale: 2 }),
  soundcheckTime: text("soundcheck_time"),
  playingTime: text("playing_time"),
  attendance: integer("attendance"),
  actualTicketSales: integer("actual_ticket_sales"),
  actualIncome: numeric("actual_income", { precision: 10, scale: 2 }),
  actualExpenses: numeric("actual_expenses", { precision: 10, scale: 2 }),
  merch: numeric("merch", { precision: 10, scale: 2 }),
  wouldDoAgain: text("would_do_again"),
  showNotes: text("show_notes"),
  // Tour linkage
  sourceTourId: integer("source_tour_id"),
  sourceStopId: integer("source_stop_id"),
  importedFromTour: boolean("imported_from_tour").notNull().default(false),
  importedAt: timestamp("imported_at", { withTimezone: true }),
  tourName: text("tour_name"),
  // Legacy columns retained so historical data isn't dropped on db push.
  // Routes read from the new field first, falling back to the legacy column.
  notes: text("notes"),
  totalIncome: numeric("total_income", { precision: 10, scale: 2 }),
  totalCost: numeric("total_cost", { precision: 10, scale: 2 }),
  totalProfit: numeric("total_profit", { precision: 10, scale: 2 }),
  actualAttendance: integer("actual_attendance"),
  actualTicketIncome: numeric("actual_ticket_income", { precision: 10, scale: 2 }),
  actualOtherIncome: numeric("actual_other_income", { precision: 10, scale: 2 }),
  actualProfit: numeric("actual_profit", { precision: 10, scale: 2 }),
  calculationSnapshot: jsonb("calculation_snapshot").$type<Record<string, unknown>>(),
  dealSource: text("deal_source", { enum: ["single_show", "tour_show", "manual", "import"] }),
  country: text("country"),
  venueName: text("venue_name"),
  city: text("city"),
  state: text("state"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertRunSchema = createInsertSchema(runsTable).omit({ id: true, createdAt: true });
export type InsertRun = z.infer<typeof insertRunSchema>;
export type Run = typeof runsTable.$inferSelect;
